### PR TITLE
Added support for rustls

### PR DESCRIPTION
**Pull request by JohnScience**

### CODE REVIEW

**Comment by JohnScience** [comment]
Not ready yet.

**Comment by ik1ne** [comment]
If you're ready, I'd like to merge this into main branch.
The CI is failing, but I think it's irrelevant to this pull request(#55 sometimes failed for no apparent reason) and my personal windows and macos machine have no failing tests.

**Comment by JohnScience** [comment]
@ik1ne Now this particular issue is addressed. However, I'm still having issues with Docker. I'll elaborate on them in a separate issue.

**Comment by ik1ne** [comment]
Thank you for the contribution, this improvement will allow the crate to be used in specific environments such as AWS Lambda.
However, enabling `rustls-tls` generates following warning:
```text
warning: unused variable: `new_client_builder`
  --> webdriver-downloader/src/traits/verification_info.rs:49:13
   |
49 |         let new_client_builder = || fantoccini::ClientBuilder::native();
   |             ^^^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_new_client_builder`
   |
   = note: `#[warn(unused_variables)]` on by default
```
So, I think verification_info.rs:48 should be `#[cfg(all(feature = "native-tls", not(feature = "rustls-tls")))]` like [fantoccini/src/wait.rs:27](https://github.com/jonhoo/fantoccini/blob/31edb300a2c16767b17e9b2d01022b285c425768/src/wait.rs#L27) does.

**Comment by JohnScience** [comment]
> Thank you for the contribution, this improvement will allow the crate to be used in specific environments such as AWS Lambda. However, enabling `rustls-tls` generates following warning:
> 
> ```
> warning: unused variable: `new_client_builder`
>   --> webdriver-downloader/src/traits/verification_info.rs:49:13
>    |
> 49 |         let new_client_builder = || fantoccini::ClientBuilder::native();
>    |             ^^^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_new_client_builder`
>    |
>    = note: `#[warn(unused_variables)]` on by default
> ```
> 
> So, I think verification_info.rs:48 should be `#[cfg(all(feature = "native-tls", not(feature = "rustls-tls")))]` like [fantoccini/src/wait.rs:27](https://github.com/jonhoo/fantoccini/blob/31edb300a2c16767b17e9b2d01022b285c425768/src/wait.rs#L27) does.

These features are meant to be mutually exclusive. This is the common practice. The proper solution is the addition of

```
#[cfg(all(feature = "rustls-tls", feature = "native-tls"))]
compile_error!("The `rutls-tls` and `native-tls` features are mutually exclusive.");
```

as [recommended](https://doc.rust-lang.org/cargo/reference/features.html#mutually-exclusive-features) in the Cargo reference.

**Comment by JohnScience** [comment]
That's the compiler message on which I settled:

```
#[cfg(all(feature = "rustls-tls", feature = "native-tls"))]
#[rustfmt::skip]
compile_error!(
r#"The `rustls-tls` and `native-tls` features are mutually exclusive.
In order to use <https://github.com/rustls/rustls>, you must disable the `native-tls` feature.

For example,

```toml
[dependencies]
webdriver-downloader = { version = "...", default-features = false, features = ["rustls-tls"] }
```

To learn more about features in Cargo, see <https://doc.rust-lang.org/cargo/reference/features.html>.
To find out which dependency enabled the mutually exclusive features, run `cargo tree -e features -i webdriver-downloader`.
"#
);
```

it's a bit verbose but helpful.

**Comment by JohnScience** [comment]
That's the compiler message on which I settled:

```rust
#[cfg(all(feature = "rustls-tls", feature = "native-tls"))]
#[rustfmt::skip]
compile_error!(
r#"The `rustls-tls` and `native-tls` features are mutually exclusive.
These two features could have been enabled simultaneously, for example, if you forgot to disable the default `native-tls` feature.
In order to use <https://github.com/rustls/rustls>, you must disable the `native-tls` feature.

For example,

'''toml
[dependencies]
webdriver-downloader = { version = "...", default-features = false, features = ["rustls-tls"] }
'''

To learn more about features in Cargo, see <https://doc.rust-lang.org/cargo/reference/features.html>.
To find out which dependency enabled the mutually exclusive features, run `cargo tree -e features -i webdriver-downloader`.
"#);
```

it's quite wordy but is helpful.

**Comment by JohnScience** [comment]
That's the compiler message on which I settled:

```rust
#[cfg(all(feature = "rustls-tls", feature = "native-tls"))]
#[rustfmt::skip]
compile_error!(
r#"The `rustls-tls` and `native-tls` features are mutually exclusive.
These two features could have been enabled simultaneously, for example, if you forgot to disable the default `native-tls` feature.
In order to use <https://github.com/rustls/rustls>, you must disable the `native-tls` feature.

For example,

'''toml
[dependencies]
webdriver-downloader = { version = "...", default-features = false, features = ["rustls-tls"] }
'''

To learn more about features in Cargo, see <https://doc.rust-lang.org/cargo/reference/features.html>.
To find out which crate(s) enabled the mutually exclusive features of `webdriver-downloader`, run `cargo tree -e features -i webdriver-downloader`.
"#);
```

it's quite wordy but is helpful.

**Comment by ik1ne** [comment]
Thank you!
While there is no testcase for this change, I've run tests manually on my machines and it all passed. (Also, these changes are addition of feature flags, not the change of default feature flag so it should be safe to merge)
The testcase for feature flags will be added with #58.

**Pull request merged**
